### ISSUE TITLE
Vagrant provisioner stops at cookbooks/drupal/attributes/default.rb

### ISSUE THREAD

**Issue by theodorosploumis** [vampd/vampd#39]
I am on Ubuntu 14.10. When I run `vagrant up` the provisioner stops on this error:

```
Recipe Compile Error in /tmp/vagrant-chef/1feace877c6bb7f795513e8e996806fa/cookbooks/drupal/attributes/default.rb
==> drupaldev: ================================================================================
==> drupaldev: 
==> drupaldev: NoMethodError
==> drupaldev: -------------
==> drupaldev: undefined method `[]' for nil:NilClass
==> drupaldev: 
==> drupaldev: Cookbook Trace:
==> drupaldev: ---------------
==> drupaldev:   /tmp/vagrant-chef/1feace877c6bb7f795513e8e996806fa/cookbooks/drupal/attributes/default.rb:61:in `block in from_file'
==> drupaldev: 
==> drupaldev:   /tmp/vagrant-chef/1feace877c6bb7f795513e8e996806fa/cookbooks/drupal/attributes/default.rb:38:in `each'
==> drupaldev: 
==> drupaldev:   /tmp/vagrant-chef/1feace877c6bb7f795513e8e996806fa/cookbooks/drupal/attributes/default.rb:38:in `from_file'
==> drupaldev: 
==> drupaldev: Relevant File Content:
==> drupaldev: ----------------------
==> drupaldev: /tmp/vagrant-chef/1feace877c6bb7f795513e8e996806fa/cookbooks/drupal/attributes/default.rb:
==> drupaldev: 
==> drupaldev:  54:    default[:drupal][:sites][site_name][:drupal][:version] = '7.26'
==> drupaldev:  55:    default[:drupal][:sites][site_name][:drupal][:registry_rebuild] = false
==> drupaldev:  56:    default[:drupal][:sites][site_name][:drupal][:install]['install_configure_form.update_status_module'] = "'array(FALSE,FALSE)'"
==> drupaldev:  57:    default[:drupal][:sites][site_name][:drupal][:install]['--clean-url'] = 1
==> drupaldev:  58:  
==> drupaldev:  59:    #Set up the docroot to be used as a default
==> drupaldev:  60:    default[:drupal][:sites][site_name][:drupal][:settings][:docroot] = ''
==> drupaldev:  61>>   docroot = site[:drupal][:settings][:docroot]
==> drupaldev:  62:    docroot_before = ''
==> drupaldev:  63:    docoot_after = ''
==> drupaldev:  64:    if !docroot.empty?
==> drupaldev:  65:      docroot_before = "#{docroot}/"
==> drupaldev:  66:      docoot_after = "/#{docroot}"
==> drupaldev:  67:    end
==> drupaldev:  68:  
==> drupaldev:  69:    default[:drupal][:sites][site_name][:drupal][:settings][:profile] = 'standard'
==> drupaldev:  70:    default[:drupal][:sites][site_name][:drupal][:settings][:files] = "#{docroot_before}sites/default/files"
==> drupaldev: 
==> drupaldev: [2015-06-30T13:20:32+00:00] ERROR: Running exception handlers
==> drupaldev: [2015-06-30T13:20:32+00:00] ERROR: Exception handlers complete
==> drupaldev: [2015-06-30T13:20:32+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> drupaldev: [2015-06-30T13:20:32+00:00] ERROR: undefined method `[]' for nil:NilClass
==> drupaldev: [2015-06-30T13:20:33+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
==> drupaldev: The previous process exited with exit code 1.

```

Here is the backtrace.

```
NoMethodError: undefined method `[]' for nil:NilClass
/tmp/vagrant-chef/1feace877c6bb7f795513e8e996806fa/cookbooks/drupal/attributes/default.rb:61:in `block in from_file'
/tmp/vagrant-chef/1feace877c6bb7f795513e8e996806fa/cookbooks/drupal/attributes/default.rb:38:in `each'
/tmp/vagrant-chef/1feace877c6bb7f795513e8e996806fa/cookbooks/drupal/attributes/default.rb:38:in `from_file'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/dsl/include_attribute.rb:39:in `block in include_attribute'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/dsl/include_attribute.rb:31:in `each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/dsl/include_attribute.rb:31:in `include_attribute'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/run_context/cookbook_compiler.rb:181:in `load_attribute_file'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/run_context/cookbook_compiler.rb:170:in `load_attributes_from_cookbook'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/run_context/cookbook_compiler.rb:110:in `block in compile_attributes'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/run_context/cookbook_compiler.rb:109:in `each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/run_context/cookbook_compiler.rb:109:in `compile_attributes'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/run_context/cookbook_compiler.rb:72:in `compile'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/run_context.rb:89:in `load'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/policy_builder/expand_node_object.rb:73:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/client.rb:265:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/client.rb:429:in `do_run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/client.rb:213:in `block in run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/client.rb:207:in `fork'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/client.rb:207:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/application.rb:236:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/application/solo.rb:226:in `block in run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/application/solo.rb:218:in `loop'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/application/solo.rb:218:in `run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/lib/chef/application.rb:55:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.2/bin/chef-solo:25:in `<top (required)>'

```

I suppose it tries to create a drupal project but cannot find some configuration. 
***Where is this coocook located?***

**Comment by timodwhit** [comment]
I believe this problem is fixed in the master branch of the cookbook but isn't set as a release and updated here. 

To resolve, make sure you have a docroot flag in your json settings for now.  https://github.com/vampd/vampd/blob/9f93d881de7d486cbe07def85a6f92c79410363a/chef/roles/example.json

**Comment by theodorosploumis** [comment]
It works this way. This should be merged with the master branch. I use the master branch.

Thanks.
